name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.10.9
  - requests
  - mlflow=2.6.0
  - scikit-learn
  - pip:
      - wandb==0.10.31
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
