name: nyc_airbnb_devs
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.6.0
  - python=3.10.9
  - ipython
  - notebook
  - jupyterlab
  - cookiecutter
  - hydra-core
  - matplotlib
  - pandas
  - git
  - pip
  - pip:
      - wandb==0.13.9
